const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/javascript');
if(req.url==='/'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><main id="scp">'+['ctc','cst','ref','res'].map(name=>fs.readFileSync(path.join(root,'docs/snips/'+name+'.html'),'utf8')).join('')+'</main><dialog id="modl"></dialog>'+fs.readFileSync(path.join(root,'docs/snips/npd.html'),'utf8'));}
if(req.url==='/favicon.ico'){res.statusCode=204;return res.end();}
if(req.url==='/core.js')return res.end(`export const CORE_INSTANCE_ID='fixture';export const getCookie=key=>({pEL:'CSR',pUID:'42'})[key];export const post=(...args)=>window.postImpl(...args);export const buildSnip=id=>{const template=document.createElement('template');if(id==='hsx')template.innerHTML=window.healthplanLayout;return template.content};export const drawDialog=({body,onClose})=>{const dialog=document.getElementById('modl'),opener=document.activeElement;dialog.replaceChildren(body);dialog.addEventListener('close',()=>{dialog.replaceChildren();opener?.focus();onClose?.(dialog)},{once:true});dialog.showModal();return {dialog,close:value=>dialog.close(value)}};export const displayAsyncModal=async(_,message)=>{window.notices.push(message)};export const displayAsyncModalSettled=async (_,message)=>{window.notices.push(message)};export const setElement=(id,value)=>{const el=document.getElementById(id);if(el)el.value=value};export const clearElement=el=>{el.value=''};export const updateNotepad=()=>{};export const error=()=>{};export const info=()=>{};export const vldt={validateForm:()=>({ok:window.formValid})};`);
if(req.url==='/lookup.js')return res.end('export class Lookup {}');if(req.url==='/search.js')return res.end('export class Search {}');if(req.url==='/contracts/member-contract.js')return res.end('export const createMemberContract=()=>({});');if(req.url==='/contracts/detail-contracts.js')return res.end('export const getDetailContract=()=>({});');
if(['/contracts/provider-contract.js','/contracts/vendor-contract.js','/contracts/subject-collection-contract.js'].includes(req.url))return res.end(fs.readFileSync(path.join(root,'wwwroot/js/modules',req.url),'utf8').replaceAll('http://localhost/core-service/','/core.js'));const file=req.url==='/incident.js'?'wwwroot/js/modules/incident.js':req.url==='/contracts/persistence-contract.js'?'wwwroot/js/modules/contracts/persistence-contract.js':null;if(file)return res.end(fs.readFileSync(path.join(root,file),'utf8').replaceAll('http://localhost/core-service/','/core.js'));
res.statusCode=404;res.end();});
(async()=>{let browser;try{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
await page.evaluate(async()=>{const {Incident}=await import('/incident.js');const {IncidentPersistence}=await import('/contracts/persistence-contract.js');const check=(ok,message)=>{if(!ok)throw Error(message)};window.notices=[];window.formValid=true;const app=new Incident({snip:{}});window.app=app;
const fill=()=>{app.incidentId='0000123';app._persistedIncidentId=null;app.timerStart=Date.now()-65000;app.isDirty=true;app._chosen={artifactType:'claims',artifactId:'0000456'};const values={contact_category:'Incoming',customer_category:'Member',reference_category:'Member',cust_mbr_id:'MEM-C',ref_mbr_id:'MEM-R',ref_type_abbr:'SUB',res_priority:'Normal',res_status:'Open',res_result:'Resolved',res_action_abbr:'ACT',res_action_code:'Action',incident_open_date:'01/02/2026',ctc_start:'10:00:00',ctc_elapsed:'00:01:05'};for(const[id,value]of Object.entries(values)){document.getElementById(id).textContent=value;}document.getElementById('ctc-fn').value='Jane';document.getElementById('ctc-ln').value='Doe';document.getElementById('ctc-note').value='Reason with "quotes" and\nnewline';document.getElementById('res-note').value='Action notes';document.getElementById('res-priority').value='Normal';document.getElementById('res-status').value='Open';document.getElementById('res-result').value='Resolved';document.getElementById('res-action-code').value='Action';document.getElementById('res-action-code').dataset.code='ACT';document.getElementById('ref-type-abbr').value='SUB';document.getElementById('ref-type').replaceChildren(new Option('Type','TYPE'));document.getElementById('ref-sub-type').replaceChildren(new Option('Subtype','SUB'));};
window.fill=fill;fill();const payload=app.collect();check(payload.cust_mbr_id==='MEM-C'&&payload.ref_mbr_id==='MEM-R','notepad is outside scp');check(payload.reference_artifact_type==='Claim'&&payload.reference_artifact_identifier==='0000456','chosen identity');check(payload.ezcapuserid===42&&payload.ezcapuser==='CSR','agent identities');check(payload.ctc_note.includes('\n')&&payload.res_note==='Action notes','notes');check(/^\d{4}-\d{2}-\d{2}$/.test(payload.incident_open_date),'ISO open date');check(payload.incident_close_date===null&&payload.ctc_elapsed==='00:01:05','timer and nullable close date');check(app.persistence.errors(payload).length===0,'valid payload');
const auth=app.persistence.collect(document,{incidentId:'I',agentId:'CSR',userId:'42',timerStart:app.timerStart,chosen:{artifactType:'authorizations',artifactId:'AUTH'}});check(auth.reference_artifact_type==='Authorization','auth singular');
let calls=0;window.postImpl=async()=>{calls++;throw Error('network failure')};check(await app.saveAndNew()===false,'network failure result');check(calls===1&&app.incidentId==='0000123'&&app.isDirty&&document.getElementById('res-note').value==='Action notes','failure preserves fields');check(!document.getElementById('scp').inert&&!document.getElementById('save-new-btn').disabled,'unlock after failure');
document.getElementById('res-priority').value='';check(await app.saveAndMore()===false&&calls===1,'validation prevents post and advance');document.getElementById('res-priority').value='Normal';
for(const result of [[],{incident_number:'I'},{csm_error:0},{incident_number:'I',csm_error:7,csm_return_value:'Rejected'}]){window.postImpl=async()=>result;check(await app.saveAndNew()===false&&app.incidentId==='0000123','malformed/server failure preserves fields');}
let release;window.postImpl=()=>{calls++;return new Promise(resolve=>{release=resolve})};const pending=app.save();await Promise.resolve();await Promise.resolve();check(await app.saveAndNew()===false,'duplicate blocked');release([{incident_number:'0000123',csm_error:'0',csm_return_value:'OK'}]);check(await pending===true&&!app.isDirty,'confirmed save');const count=calls;check(await app.save()===true&&calls===count,'confirmed insert not repeated');
fill();let outgoing;window.postImpl=async(handler,request)=>{check(handler==='ParameterSQL','handler');if(request.spName==='scp.get_next_csino')return [{CSINO:'NEXT'}];outgoing=request;return [{incident_number:'0000123',csm_error:0,csm_return_value:'OK'}]};check(await app.saveAndMore()===true,'save more');check(outgoing.spName==='scp.set_incident'&&outgoing.parameters[0].Key==='@p_csi_data'&&outgoing.parameters[0].Type==='varchar','SQL request');check(JSON.parse(outgoing.parameters[0].Value).reference_artifact_identifier==='0000456','serialized reference');check(app.incidentId==='NEXT'&&document.getElementById('ctc-fn').value==='Jane'&&document.getElementById('cust_mbr_id').textContent==='MEM-C','more retains contact/customer');check(document.getElementById('res-note').value===''&&document.getElementById('res-action-code').dataset.code===''&&!app._chosen.artifactId,'more clears reference/resolution');app._stopTimer();
fill();check(await app.saveAndNew()===true,'save new');check(app.incidentId===null&&document.getElementById('ctc-fn').value===''&&document.getElementById('cust_mbr_id').textContent==='','new clears form');check(!app._saveInProgress,'save lock released');
fill();app.incidentId=null;app.timerStart=null;let numberRelease;let reservations=0;let savedRequest;
window.postImpl=async(_,request)=>{if(request.spName==='scp.get_next_csino'){reservations++;return new Promise(resolve=>{numberRelease=resolve})}savedRequest=request;return [{incident_number:'READY',csm_error:0}]};
const initialization=app._ensureContact();const saving=app.save();await Promise.resolve();check(reservations===1&&!savedRequest,'save waits for contact initialization: '+reservations+'/'+!!savedRequest+'/'+!!app._contactPromise+'/'+app.incidentId);numberRelease([{CSINO:'READY'}]);await initialization;check(await saving===true&&JSON.parse(savedRequest.parameters[0].Value).incident_number==='READY','initialized incident submitted');app._stopTimer();
const persistence=new IncidentPersistence({post:async()=>[{csm_error:0,incident_number:'ID'}]});check((await persistence.insert(payload)).incidentNumber==='ID','adapter response');
});await page.evaluate(layout=>{window.healthplanLayout=layout;app.lookupStore.arrHealthplan=[['HP1','First Health Plan'],['HP2','Second Health Plan']];window.healthCalls=[];window.postImpl=async(_,request)=>{healthCalls.push(request);return [{HPCODE:request.parameters[0].Value,HPNAME:request.parameters[0].Value==='HP1'?'First Health Plan':'Second Health Plan'}]};document.getElementById('cc-hpl').checked=true;document.getElementById('customer_category').textContent='Health Plan';window.healthPending=app.drawSearch('healthplan','customer');},fs.readFileSync(path.join(root,'docs/snips/hsx.html'),'utf8'));
await page.getByRole('dialog').waitFor({state:'visible'});await page.locator('#search-btn').click();assert.equal(await page.getByRole('dialog').isVisible(),true);await page.locator('#qry-health-plan').selectOption('HP1');await page.locator('#search-btn').click();
await page.evaluate(async()=>{await healthPending;if(document.getElementById('customer-id').value!=='First Health Plan'||document.getElementById('cust_hpl_abbr').textContent!=='HP1'||document.getElementById('cust_hpl_name').textContent!=='First Health Plan')throw Error('health plan display/notepad');if(healthCalls[0].parameters[0].Key!=='@p_healthplan_code'||healthCalls[0].parameters[0].Value!=='HP1')throw Error('health plan parameter');if(app.collect().cust_hpl_abbr!=='HP1')throw Error('health plan persistence');window.healthPending=app.drawSearch('healthplan','customer');});
await page.getByRole('dialog').waitFor({state:'visible'});await page.keyboard.press('Escape');await page.evaluate(async()=>{await healthPending;if(healthCalls.length!==1||document.getElementById('cust_hpl_abbr').textContent!=='HP1')throw Error('cancel changes selection');window.healthPending=app.drawSearch('healthplan','customer');});
await page.getByRole('dialog').waitFor({state:'visible'});await page.locator('#qry-health-plan').selectOption('HP2');await page.locator('#qry-health-plan').press('Enter');await page.evaluate(async()=>{await healthPending;if(document.getElementById('customer-id').value!=='Second Health Plan')throw Error('keyboard selection');if(app._resolveSameReference()!==false)throw Error('health plan accepted as same');document.getElementById('cc-prv').checked=true;app.onCategoryChange({target:document.getElementById('cc-prv')},'customer');if(document.getElementById('cust_hpl_abbr').textContent||document.getElementById('cust_hpl_name').textContent)throw Error('stale health plan fields');app.lookupStore.arrHealthplan=[];await app.drawSearch('healthplan','customer');if(!notices.at(-1).includes('No health plans'))throw Error('empty list');});
assert.deepEqual(errors,[]);console.log('PASS: SQL field collection, JSON/reference identity, dates/timer/user, validation, failure preservation, duplicate prevention, insert-only guard, Save & More/New, and lock cleanup');}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
