const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');const {chromium}=require('playwright');
const core=process.env.CORE_ROOT,root=path.resolve(__dirname,'..');const ts=require(path.join(core,'node_modules/typescript'));const src=fs.readFileSync(path.join(root,'wwwroot/js/modules/incident.js'),'utf8');const start=src.indexOf('    async showReferenceCollections('),end=src.indexOf('    // -----------------------------------------',src.indexOf('    _refreshCollectionViews(',start));
const fixture="import * as Core from '/core.js';import {createMemberContract} from '/contracts/member-contract.js';import {createProviderContract} from '/contracts/provider-contract.js';import {createVendorContract} from '/contracts/vendor-contract.js';export class Fixture {"+src.slice(start,end)+" _showDetail(){throw Error('unexpected detail')} _clearReferenceSystem(){this._rmgr?.destroy();this._clct?.destroy();this._rmgr=null;this._clct=null;} }";
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/javascript');if(req.url==='/'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><div class="clct dnd"></div>');}if(req.url==='/favicon.ico'){res.statusCode=204;return res.end();}if(req.url==='/fixture.js')return res.end(fixture);if(req.url==='/core.js')return res.end("export * from '/rmgr.js';export * from '/clct.js';export * from '/tblm.js';export * from '/fltr.js';export const post=(...args)=>window.mockPost(...args);");if(/^\/contracts\/[a-z-]+\.js$/.test(req.url))return res.end(fs.readFileSync(path.join(root,'wwwroot/js/modules',req.url),'utf8').replaceAll('http://localhost/core-service/','/core.js'));const name=req.url.slice(1).replace(/\.js$/,'');if(!/^[a-z]+$/.test(name)){res.statusCode=404;return res.end();}const file=path.join(core,'src/js',name+'.ts');if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.end(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.ESNext}}).outputText.replace(/from (["'])\.\/([a-z]+)\1/g,'from "/$2.js"'));});
(async()=>{let browser;try{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
await page.evaluate(async()=>{const {Fixture}=await import('/fixture.js');const check=(ok,message)=>{if(!ok)throw Error(message)};const calls=[];let release;let delay=false;window.mockPost=async(_,payload)=>{calls.push(payload);if(delay&&payload.spName==='scp.get_provider_specialty')await new Promise(resolve=>{release=resolve});return ({
'scp.get_provider_specialty':[{PROV_KEYID:'P','Specialty':'Cardiology',Code:'C',Priority:'Primary','Cert. Date':'2026-01-02',Verified:'Yes'},{PROV_KEYID:'P','Specialty':'Neurology',Code:'N',Priority:'Secondary','Cert. Date':'2025-12-31',Verified:'No'}],
'scp.get_provider_location':[{PROV_KEYID:'P','Street 1':'<span title="Office">Main St</span>',City:'City'},{PROV_KEYID:'P','Street 1':'Second St',City:'City'}],
'scp.get_vendor_roster':[{VENDORID:'V','Vendor Name':'Vendor','Provider Name':'Alpha','Provider NPI':'001'},{VENDORID:'V','Vendor Name':'Vendor','Provider Name':'Beta','Provider NPI':'002'}],
'scp.get_vendor_address':[{VENDORID:'V','Vendor Name':'<span title="Alias">Vendor</span>',Address:'Main'},{VENDORID:'V','Vendor Name':'Vendor',Address:'Second'}],
'scp.list_member_eligibility':[], 'scp.list_member_claim':[],'scp.list_member_authorization':[],'scp.list_member_incident':[],'scp.list_member_condition':[],
})[payload.spName]||[]};const app=new Fixture();await app.showReferenceCollections({domain:'PROVIDER',subjectId:'P'});check([...document.querySelectorAll('.clct-tab')].map(t=>t.textContent).join('|')==='Specialty (2)|Locations (2)','provider tabs/counts');check(app._rmgr.getView('specialties').totalCount===2,'same subject ID keeps distinct specialties');const table=document.getElementById('specialty-table');check(table.tHead.textContent.includes('Cert. Date')&&!table.tHead.textContent.includes('PROV_KEYID'),'provider columns');check(table.tBodies[0].rows[0].cells[3].textContent==='01/02/2026','date format');table.tHead.rows[0].cells[3].click();check(table.tBodies[0].rows[0].cells[0].textContent==='Neurology','date sort');check(document.getElementById('location-table').querySelector('span').title==='Office','location HTML');check(document.querySelector('.clct-filter').hidden&&document.querySelector('.clct-show-detail').hidden,'nonchoosable/filter-free provider');check(calls.slice(0,2).every(c=>c.parameters[0].Key==='@p_PROV_KEYID'&&c.parameters[0].Value==='P'),'provider parameters');
await app.showReferenceCollections({domain:'VENDOR',subjectId:'V'});check([...document.querySelectorAll('.clct-tab')].map(t=>t.textContent).join('|')==='Roster (2)|Address (2)','vendor tabs/counts');check(app._rmgr.getView('roster').totalCount===2&&app._rmgr.getView('addresses').totalCount===2,'distinct vendor rows');check(document.getElementById('address-table').querySelector('span').title==='Alias','address HTML');check(calls.slice(2,4).every(c=>c.parameters[0].Key==='@p_VEN_KEYID'&&c.parameters[0].Value==='V'),'vendor parameter is vendor number');
await app.showReferenceCollections({domain:'MEMBER',subjectId:'M'});check(document.querySelectorAll('.clct-tab').length===5,'member tabs retained');
delay=true;const pending=app.showReferenceCollections({domain:'PROVIDER',subjectId:'old'});await Promise.resolve();await Promise.resolve();await app.showReferenceCollections({domain:'VENDOR',subjectId:'new'});release();await pending;check(app._referenceDomain==='VENDOR'&&document.getElementById('roster-table'),'stale provider load cannot replace vendor');
window.mockPost=async()=>[];await app.showReferenceCollections({domain:'VENDOR',subjectId:'empty'});check(app._rmgr.getViews().every(v=>v.totalCount===0),'empty counts');check(document.querySelector('.clct-slot').textContent.length>0,'empty message');
window.mockPost=async()=>{throw Error('failed')};let failed=false;try{await app.showReferenceCollections({domain:'PROVIDER',subjectId:'fail'})}catch{failed=true}check(failed,'failure propagated');app._clearReferenceSystem();
});assert.deepEqual(errors,[]);console.log('PASS: provider/vendor contracts, parameter identities, full row counts, labels/date sorting/HTML, empty/error behavior, member tabs, nonchoosable panels, and replacement races');}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
